name: Android CI

on:
  push:
    # branches: [ "dev" ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1
        with:
          log-accepted-android-sdk-licenses: false

      - name: Test Project (:app)
        run: |
          chmod +x gradlew
          ./gradlew app:check app:test --no-daemon
        env:
          APK_KEYSTORE_PASSWORD: ${{ secrets.APK_KEYSTORE_PASSWORD }}
          APK_ALIAS: ${{ secrets.APK_ALIAS }}
          APK_ALIAS_PASSWORD: ${{ secrets.APK_ALIAS_PASSWORD }}

  Build:
    runs-on: ubuntu-latest
    needs: Test
    permissions:
      contents: write # Allow this job to create releases
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1
        with:
          log-accepted-android-sdk-licenses: false

      - name: Decode Keystore
        run: |
          mkdir -p $RUNNER_TEMP
          echo "$ENCODED_KEYSTORE" | base64 -di > "$RUNNER_TEMP/keystore.jks"
        env:
          ENCODED_KEYSTORE: ${{ secrets.APK_KEYSTORE }}

      - name: Build Project (:app)
        run: |
          chmod +x gradlew
          ./gradlew app:assemble app:bundle --no-daemon
        env:
          APK_KEYSTORE_PASSWORD: ${{ secrets.APK_KEYSTORE_PASSWORD }}
          APK_ALIAS: ${{ secrets.APK_ALIAS }}
          APK_ALIAS_PASSWORD: ${{ secrets.APK_ALIAS_PASSWORD }}

      - name: Create Release
        id: release
        uses: actions/create-release@v1.1.4
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: Imaginator.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload AAB Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: app/build/outputs/bundle/release/app-release.aab
          asset_name: Imaginator.aab
          asset_content_type: application/x-authorware-bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
